### ISSUE TITLE
Test suite fails due to unexpected external encoding.

### ISSUE THREAD

**Issue by voxik** [TwP/logging#114]
In Fedora builders, there is set LANG=C, so if I execute the test suite, I observe following test errors:

```
$ ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
Loaded suite -e
Started
.......................F
===============================================================================
Failure: test_force_encoding(TestLogging::TestAppenders::TestBufferedIO)
/builddir/build/BUILD/rubygem-logging-2.0.0/usr/share/gems/gems/logging-2.0.0/test/appenders/test_buffered_io.rb:207:in `test_force_encoding'
     204:         assert_nil(readline)
     205: 
     206:         @appender.append event_a
  => 207:         assert_equal " INFO  TestLogger : #{a}\n", readline
     208:         assert_equal " INFO  TestLogger : #{b.force_encoding('UTF-8')}\n", readline
     209:         assert_equal " INFO  TestLogger : #{a}\n", readline
     210:         assert_nil(readline)
<" INFO  TestLogger : \u00FCmlaut\n">(UTF-8) expected but was
<" INFO  TestLogger : \xC3\xBCmlaut\n">(US-ASCII)

diff:
?  INFO  TestLogger : ümlaut
?                     ü     
  
? Encoding: UTF-8    
?            S  ASCII
===============================================================================
...F
===============================================================================
Failure: test_encoding(TestLogging::TestAppenders::TestFile)
/builddir/build/BUILD/rubygem-logging-2.0.0/usr/share/gems/gems/logging-2.0.0/test/appenders/test_file.rb:112:in `test_encoding'
     109: 
     110:         lines = File.readlines(log)
     111:         assert_equal "A normal line of text\n", lines[0]
  => 112:         assert_equal "ümlaut\n", lines[1]
     113: 
     114:         cleanup
     115:       end
<"\u00FCmlaut\n">(UTF-8) expected but was
<"\xC3\xBCmlaut\n">(US-ASCII)

diff:
? ümlaut
? ü     
  
? Encoding: UTF-8    
?            S  ASCII
===============================================================================
...............................................................................
.....................................................................

Finished in 7.265402428 seconds.
------
176 tests, 1096 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
98.8636% passed
------
24.22 tests/s, 150.85 assertions/s
```

**Comment by TwP** [comment]
Do you have a script that reproduces this error? I'm not sure what "Fedora builders" is and I am not familiar with the `LANG=C` setting. I guess I need a bit more context around this error.

**Comment by voxik** [comment]
This is about settings of locales. The LANG environment variable specifies what language will your application use and also what Ruby's external encoding will be. This is setting of my specific system:

```
$ env | grep LANG
LANG=cs_CZ.utf8
```

If I was Japanese, it would be probably ja_JP.SJIS.

Since Fedora [1] builders are language agnostic, they are using LANG=C, which is ASCII encoding. So to reproduce my case, you can run ```LANG=C ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'```.

I believe that the second failure is just test issue, the fix should be something like ```File.readlines(log, :external_encoding => 'UTF-8')```, since you written the file and you know the encoding. But the first one seems to be trickier. Not sure what the fix should be.


[1] https://getfedora.org/

**Comment by voxik** [comment]
Thank you.

**Comment by TwP** [comment]
It was easy to reproduce once I did `export LANG=C` in a shell environment. The fix was straightforward enough, too. Thanks for reporting the bug.
