### ISSUE TITLE
Rolling file logger fails to find log file

### ISSUE THREAD

**Issue by grossjo** [TwP/logging#148]
I get this error, when running specs in parallel.
I have a number of separate processes spun up to run rspec tests. And then randomly we get this error on a  few tests.
Any ideas?

```
Errno::ENOENT:
15:05:53        No such file or directory @ rb_file_s_mtime - /data/build//log/test.log._copy_
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/appenders/rolling_file.rb:169:in `mtime'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/appenders/rolling_file.rb:169:in `roll_required?'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/appenders/rolling_file.rb:153:in `canonical_write'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/appenders/buffering.rb:285:in `write'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/appender.rb:81:in `append'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/logger.rb:397:in `block in log_event'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/logger.rb:397:in `each'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/logger.rb:397:in `log_event'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/logger.rb:398:in `log_event'
15:05:53      # /usr/local/bundle/gems/logging-2.1.0/lib/logging/logger.rb:92:in `debug'
```

**Comment by TwP** [comment]
Looks like a race condition. Here is line 169 in the `rolling_file.rb` file:

```ruby
return false if ::File.exist?(copy_file) && (Time.now - ::File.mtime(copy_file)) < 180
```

The `copy_file` exists on the left-hand side of the `&&` condition. But by the time the right-hand side of the `&&` condition is executed, the file has been deleted.

The simple fix is to skip the existence check and just rescue the `ENOENT` error raised by `mtime` if it happens.

```ruby
mtime = begin
  File.mtime(copy_file)
rescue Errno::ENOENT
  nil
end
return false if mtime && (Time.now - copy_file) < 180
```
Thoughts? :thought_balloon:
