### ISSUE TITLE
Get CancelledKeyException at end of rspec suite in JRuby

### ISSUE THREAD

**Issue by keithrbennett** [TwP/logging#62]
When running an rspec test suite in JRuby on Mac OS (Java SE 1.6), I get the following error on exit (the tests all passed):

```
Exception in thread "RubyThread-14: /Users/kbennett/.rvm/gems/jruby-1.7.3/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:320" java.nio.channels.CancelledKeyException
    at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:55)
    at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:69)
    at sun.nio.ch.KQueueSelectorImpl.updateSelectedKeys(KQueueSelectorImpl.java:105)
    at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:74)
    at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
    at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
    at org.jruby.util.io.SelectBlob.doSelect(SelectBlob.java:257)
```

(complete stack trace is at https://gist.github.com/keithrbennett/5570290).

**Comment by olleolleolle** [comment]
As JRuby no longer supports Java 6, I think this issue can be closed.

**Comment by TwP** [comment]
I've not been keeping up on the JRuby front. But yes, this issue is definitely a little stale. Closing.

**Comment by keithrbennett** [comment]
Yikes! My apologies for never having answered you.

- Keith
